# Generated by Django 4.1.3 on 2022-12-11 08:32

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите понятное название ингредиента.', max_length=1000, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='От чайной ложки до ковша экскаватора.', max_length=1000, verbose_name='Единицы измерения ингредиента')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1!')], verbose_name='Количество ингредиента')),
            ],
            options={
                'default_related_name': 'ingridientsquantity',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название рецепта,отражающее его суть или просто интересное название :)', max_length=255, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='recipes/media/', verbose_name='Картинка')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text=('Укажите примерное время,необходимое для приготовления Вашего блюда.',), validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1 мин.')], verbose_name='Время приготовления')),
                ('text', models.TextField(help_text='Напишите рецепт блюда,чтобы его смог приготовить любой желающий!', verbose_name='Описание рецепта')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория к которой Вы бы отнесли свой рецепт.Одним словом.', max_length=100, verbose_name='Тег рецепта')),
                ('slug', models.SlugField(help_text='Добавьте уникальный ID для тега', unique=True, verbose_name='Уникальное название тега')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='HEX-код цвета')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_recipe', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Список покупок',
            },
        ),
    ]
