# Generated by Django 4.1.3 on 2022-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_userfavoriterecipes_userfavoriterecipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsinrecipe',
            name='unique_ingredient_in_recipe',
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Единственность ингредиента в рецепте'),
        ),
    ]
