# Generated by Django 4.2.3 on 2023-07-12 11:11

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230710_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=recipes.models.image_recipe_upload_user_folder, verbose_name='Картинка'),
        ),
    ]
